=== tangl-services/tangl-dev/bucket-schemas/meta-bucket-elemennt-json-example.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$ref": "#/definitions/ElementRoot",
    "definitions": {
        "ElementRoot": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "Id": {
                    "type": "integer"
                },
                "Guid": {
                    "type": "string",
                    "format": "uuid"
                },
                "ElementGuid": {
                    "type": "string",
                    "format": "uuid"
                },
                "Name": {
                    "type": "string"
                },
                "Type": {
                    "type": "string"
                },
                "Category": {
                    "type": "string"
                },
                "Meta": {
                    "$ref": "#/definitions/Meta"
                }
            },
            "required": [
                "Category",
                "ElementGuid",
                "Guid",
                "Id",
                "Meta",
                "Name",
                "Type"
            ],
            "title": "ElementRoot"
        },
        "Meta": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "Element": {
                    "$ref": "#/definitions/Element"
                }
            },
            "required": [
                "Element"
            ],
            "title": "Meta"
        },
        "Element": {
            "type": "object",
            "additionalProperties": true,
            "properties": {
                "File": {
                    "type": "string"
                },
                "Pars": {
                    "$ref": "#/definitions/Pars"
                },
                "Materials": {
                    "$ref": "#/definitions/Materials"
                },
                "Layers": {
                    "$ref": "#/definitions/Layers"
                },
                "Level": {
                    "$ref": "#/definitions/Level"
                },
                "Boundings": {
                    "$ref": "#/definitions/Boundings"
                },
                "Link": {
                    "$ref": "#/definitions/Link"
                }
            },
            "required": [
                "File",
                "Link",
                "Pars"
            ],
            "title": "Element"
        },
        "Boundings": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "Bottom": {
                    "type": "integer"
                },
                "Top": {
                    "type": "integer"
                }
            },
            "required": [
                "Bottom",
                "Top"
            ],
            "title": "Boundings"
        },
        "Layers": {
            "type": "object",
            "additionalProperties": false,
              "patternProperties":{
                "([0-9]+)$": {}
            },
            "title": "Layers"
        },
        "Layer": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "Function": {
                    "type": "string"
                },
                "Material": {
                    "type": "string"
                },
                "Width": {
                    "type": "integer"
                },
                "Volume": {
                    "type": "number"
                },
                "Area": {
                    "type": "number"
                }
            },
            "required": [
                "Area",
                "Function",
                "Volume",
                "Width"
            ],
            "title": "Layer"
        },
        "Level": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "Name": {
                    "type": "string"
                },
                "Elevation": {
                    "type": "integer"
                }
            },
            "required": [
                "Elevation",
                "Name"
            ],
            "title": "Level"
        },
        "Link": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "IsLinkElement": {
                    "type": "boolean"
                }
            },
            "required": [
                "IsLinkElement"
            ],
            "title": "Link"
        },
        "Materials": {
            "type": "object",
            "additionalProperties": false,
              "patternProperties":{
                "([0-9]+)$": {}
            },
            "title": "Materials"
        },
        "Material": {
            "type": "object",
            "additionalProperties": true,
            "properties": {
                "Material": {
                    "type": "string"
                },
                "Volume": {
                    "type": "number"
                },
                "Area": {
                    "type": "number"
                },
                "Layers": {
                    "$ref": "#/definitions/Layers"
                }
            },
            "required": [
                "Area",
                "Layers",
                "Material",
                "Volume"
            ],
            "title": "Material"
        },
        "Pars": {
            "type": "object",
            "additionalProperties": true,
            "title": "Pars"
        }
    }
}

=== tangl-services/tangl-dev/bucket-schemas/meta-bucket-elemennt-json-schema.json
{
    "Id": 11773953,
    "Guid": "3d914a58-9b77-43b8-8680-6ada56b3b978",
    "ElementGuid": "8f6481db-8caf-44b9-ad81-064ee95dc1bf",
    "Name": "НР_Парапет(200)_Тротуарная плитка-200х100х80",
    "Type": "НР_Парапет(200)_Тротуарная плитка-200х100х80",
    "Category": "Стены",
    "Meta": {
        "Element": {
            "Name": "НР_Парапет(200)_Тротуарная плитка-200х100х80",
            "Id": 11773953,
            "Category": "Стены",
            "Type": "НР_Парапет(200)_Тротуарная плитка-200х100х80",
            "File": "048_22_Северный Химмаш_этап 1_д1_П_АР_ФХ_r.grigoriev",
            "Pars": {
                "_Положение": "Кровля",
                "_Этаж": "Кровля",
                "_Этаж спецификации": 0,
                "Включить аналитическую модель": 0,
                "Граница помещения": 1,
                "Длина": 35002,
                "Зависимость сверху": {
                    "Name": "Кровля",
                    "Id": 10645004,
                    "Category": "Уровни",
                    "Type": "Отметка уровня с именем 2.5 мм",
                    "File": "048_22_Северный Химмаш_этап 1_д1_П_АР_ФХ_r.grigoriev",
                    "Pars": {
                        "_Этаж": "Кровля",
                        "Имя": "Кровля",
                        "Несущие конструкции": 0,
                        "Построение этажа": 1,
                        "Рабочий набор": "Оси и аннотации",
                        "Расчетная высота": 500,
                        "Редактирует": "",
                        "Тип": {
                            "Name": "Отметка уровня с именем 2.5 мм",
                            "Id": 10387884,
                            "Category": "Уровни",
                            "Pars": {
                                "Базовая отметка": 0,
                                "Вес линий": 1,
                                "Имя семейства": "Уровень",
                                "Имя типа": "Отметка уровня с именем 2.5 мм",
                                "Обозначение": {
                                    "RefIdx": 2922
                                },
                                "Образец линий": {
                                    "RefIdx": 2923
                                },
                                "Рабочий набор": "Типы уровней",
                                "Редактирует": "",
                                "Стандартное обозначение второго конца": 1,
                                "Стандартное обозначение первого конца": 1,
                                "Цвет": 16711680
                            },
                            "Link": {
                                "IsLinkElement": false
                            }
                        },
                        "Фасад": 49300
                    },
                    "Link": {
                        "IsLinkElement": false
                    }
                },
                "Зависимость снизу": {
                    "Name": "Кровля",
                    "Id": 10645004,
                    "Category": "Уровни",
                    "Type": "Отметка уровня с именем 2.5 мм",
                    "File": "048_22_Северный Химмаш_этап 1_д1_П_АР_ФХ_r.grigoriev",
                    "Pars": {
                        "_Этаж": "Кровля",
                        "Имя": "Кровля",
                        "Несущие конструкции": 0,
                        "Построение этажа": 1,
                        "Рабочий набор": "Оси и аннотации",
                        "Расчетная высота": 500,
                        "Редактирует": "",
                        "Тип": {
                            "Name": "Отметка уровня с именем 2.5 мм",
                            "Id": 10387884,
                            "Category": "Уровни",
                            "Pars": {
                                "Базовая отметка": 0,
                                "Вес линий": 1,
                                "Имя семейства": "Уровень",
                                "Имя типа": "Отметка уровня с именем 2.5 мм",
                                "Обозначение": {
                                    "RefIdx": 2922
                                },
                                "Образец линий": {
                                    "RefIdx": 2923
                                },
                                "Рабочий набор": "Типы уровней",
                                "Редактирует": "",
                                "Стандартное обозначение второго конца": 1,
                                "Стандартное обозначение первого конца": 1,
                                "Цвет": 16711680
                            },
                            "Link": {
                                "IsLinkElement": false
                            }
                        },
                        "Фасад": 49300
                    },
                    "Link": {
                        "IsLinkElement": false
                    }
                },
                "Использование в конструкции": 0,
                "Линия привязки": 3,
                "Неприсоединенная высота": 1480,
                "Несущие конструкции": 0,
                "Объем": 10.3605928,
                "Площадь": 51.8029671,
                "Позиция": "",
                "Положение стены": 1,
                "Примыкание сверху": 0,
                "Примыкание снизу": 0,
                "Рабочий набор": "Архитектура",
                "Размер выступа сверху": 0,
                "Размер выступа снизу": 0,
                "Редактирует": "r.grigoriev",
                "Связь с формообразующим элементом": 0,
                "Смещение сверху": 1700,
                "Смещение снизу": 220,
                "Стадия возведения": {
                    "Name": "По умолчанию",
                    "Id": 3,
                    "Category": "Стадии",
                    "Pars": {
                        "Имя": "По умолчанию",
                        "Порядковый номер": 1,
                        "Рабочий набор": "Параметры стадий",
                        "Редактирует": ""
                    },
                    "Link": {
                        "IsLinkElement": false
                    }
                },
                "Тип": {
                    "Name": "НР_Парапет(200)_Тротуарная плитка-200х100х80",
                    "Id": 12444931,
                    "Category": "Стены",
                    "Pars": {
                        "Группа модели": "Наружные стены",
                        "Имя семейства": "Базовая стена",
                        "Имя типа": "НР_Парапет(200)_Тротуарная плитка-200х100х80",
                        "Код по классификатору": "",
                        "Коэффициент поглощения": 0.1,
                        "Маркировка типоразмера": "",
                        "Огибание в местах вставки элементов": 0,
                        "Огибание в торцах стен": 0,
                        "Описание": "Кладка",
                        "Описание по классификатору": "",
                        "Рабочий набор": "Типы стен",
                        "Редактирует": "",
                        "Толщина": 200,
                        "Функция": 0,
                        "Цвет штриховки при низкой детализации": 128,
                        "Шероховатость": 1,
                        "Штриховка при низкой детализации": {
                            "Name": "<Сплошная заливка>",
                            "Id": 66,
                            "Pars": {
                                "Рабочий набор": "Штриховки",
                                "Редактирует": ""
                            },
                            "Link": {
                                "IsLinkElement": false
                            }
                        }
                    },
                    "Link": {
                        "IsLinkElement": false
                    }
                }
            },
            "Materials": {
                "0": {
                    "Material": "АСК_Плитка тротуарная_Берит_Прямоугольник 200x100x80_Серый",
                    "Volume": 10.36059284210205,
                    "Area": 51.8029670715332,
                    "Класс": "Плитка",
                    "Плавность": 50,
                    "Описание": "Плитка тротуарная Берит Прямоугольник 200х100х80 (серый)",
                    "Прозрачность": 0,
                    "Цвет": 12632256,
                    "Свечение": 0,
                    "Группа модели": "Наружная отделка",
                    "Блеск": 64,
                    "Имя": "АСК_Плитка тротуарная_Берит_Прямоугольник 200x100x80_Серый",
                    "Стоимость": 0,
                    "Рабочий набор": 10,
                    "Layers": {
                        "0": {
                            "Function": "Structure",
                            "Volume": 10.36059284210205,
                            "Area": 51.8029670715332,
                            "Width": 200
                        }
                    }
                }
            },
            "Layers": {
                "0": {
                    "Function": "Structure",
                    "Material": "АСК_Плитка тротуарная_Берит_Прямоугольник 200x100x80_Серый",
                    "Width": 200,
                    "Volume": 10.36059284210205,
                    "Area": 51.8029670715332
                }
            },
            "Level": {
                "Name": "Кровля",
                "Elevation": 49300
            },
            "Boundings": {
                "Bottom": 49520,
                "Top": 51000
            },
            "Link": {
                "IsLinkElement": false
            }
        }
    }
}
